#line 1 "Lexer.flex.cpp"

#line 3 "Lexer.flex.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 128
#define YY_END_OF_BUFFER 129
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[435] =
    {   0,
        0,    0,    2,    2,   17,   17,    0,    0,  129,  128,
        6,  128,  122,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,  128,  128,  124,  128,    2,    4,    3,
        7,   14,   22,   17,   25,   26,   27,    0,   28,    0,
        1,  125,  123,   23,    0,   46,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   61,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   75,    0,   77,   81,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    2,    3,
        3,    5,    7,   20,   21,   18,   19,   11,   12,   13,
        9,   15,   10,   16,    0,   25,   24,    0,   31,   44,
        0,   39,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   72,    0,    0,   78,
        0,    0,    0,   85,    0,    0,    0,   89,    0,    0,
        0,    0,    0,    0,   96,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  110,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    8,
       42,   31,   43,   40,   41,   34,   35,   36,   32,   37,
       33,   38,    0,    0,   47,   48,    0,   50,   51,    0,
       53,    0,    0,    0,    0,    0,    0,    0,    0,   63,
       64,    0,    0,    0,    0,    0,    0,    0,    0,   74,
        0,    0,   82,   83,    0,   86,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  107,    0,  109,    0,  112,    0,
        0,    0,    0,    0,    0,  119,    0,    0,    0,    8,
       29,    0,    0,   49,   52,    0,   55,   56,    0,    0,

        0,    0,    0,   65,    0,    0,   68,    0,   70,   71,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   98,    0,  100,    0,    0,    0,    0,
        0,    0,  108,    0,  113,    0,    0,    0,  117,    0,
        0,  121,    0,    8,    0,    0,    0,    0,    0,    0,
        0,   62,    0,   67,    0,    0,    0,    0,    0,    0,
       87,    0,    0,   91,    0,    0,   94,    0,   97,   99,
      101,    0,  103,  104,  105,  106,  111,    0,  115,  116,
        0,    0,    0,    8,    0,    0,   54,    0,   58,   59,
        0,    0,   69,   73,    0,    0,    0,    0,    0,    0,

       92,    0,    0,    0,    0,  118,    0,    0,    0,   45,
       57,   60,   66,   76,    0,   80,    0,   88,   90,    0,
       95,    0,    0,  120,  126,   30,    0,   79,   84,   93,
        0,  114,  102,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    1,    1,    1,    1,    5,    1,
        1,    6,    7,    1,    1,    1,    8,    9,   10,   10,
       10,   10,   10,   10,   10,   11,   11,    1,    1,    1,
       12,    1,    1,   13,   11,   11,   11,   11,   11,   11,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   14,    1,    1,    1,    1,   15,   16,   17,   18,

       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,    1,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   40,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   41,    1,    1,    1,    1,    1,    1,    1,   42,

        1,    1,   43,    1,   44,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[45] =
    {   0,
        1,    2,    1,    3,    1,    4,    1,    1,    5,    5,
        5,    1,    1,    6,    5,    5,    5,    5,    5,    5,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[448] =
    {   0,
        0,    0,   43,   44,   49,   50,   53,   54,  557,  558,
      558,   54,  558,  550,   38,  543,  550,   44,   46,   52,
       43,   45,   64,  524,   68,  523,   51,   67,   74,  532,
       87,   76,   89,   63,  528,  558,  506,    0,  558,  105,
        0,  558,  558,  120,    0,  558,  544,   89,  558,  156,
      558,  109,  558,  558,  515,  558,  514,  516,  525,  510,
       94,   50,  527,  513,  111,  506,  507,  504,  518,  100,
      510,  104,  506,  503,  500,  558,  502,  498,  558,  121,
      503,  493,  502,  503,  507,  492,  505,  492,   93,  506,
      130,  483,  505,  490,  479,  128,  494,  116,  108,  486,

      487,  485,  135,  146,  482,  151,  489,  469,    0,  148,
      156,  558,    0,  558,  558,  558,  558,  558,  558,  558,
      558,  558,  558,  558,    0,    0,  558,  173,  177,  558,
      178,  183,  190,  192,  194,  196,  198,  200,  202,  204,
      206,  210,  477,  490,  482,  492,  487,  486,  487,  472,
      485,  469,  181,  477,  484,  479,  481,  477,  468,  466,
      467,  473,  459,  475,  470,  473,  468,  457,  459,  465,
      458,  461,  462,  558,  454,  460,  447,  558,  446,  461,
      440,  441,  447,  454,  558,  437,  437,  443,  437,  448,
      199,  199,  433,  433,  435,  444,  558,  443,  428,  432,

      437,  443,  428,  428,  422,  436,  438,  426,  407,    0,
      558,  558,  558,  558,  558,  558,  558,  558,  558,  558,
      558,  558,  229,  419,  558,  558,  424,  558,  558,  426,
      558,  422,  414,  412,  421,  416,  408,  420,  414,  558,
      558,  406,  415,  406,  417,  409,  416,  400,  417,  558,
      408,  399,  558,  558,  397,  558,  411,  412,  395,  398,
      409,  404,  399,  392,  389,  400,  399,  384,  387,  390,
      391,  385,  395,  394,  558,  374,  558,  380,  558,  387,
      388,  386,  374,  383,  369,  558,  369,  382,  359,    0,
      558,  241,  384,  558,  558,  379,  558,  558,  369,  381,

      369,  379,  374,  558,  375,  363,  558,  364,  558,  558,
      372,  371,  153,  357,  353,  352,  361,  351,  349,  364,
      363,  351,  350,  558,  359,  558,  356,  360,  357,  352,
      339,  349,  558,  350,  558,  352,  349,  334,  558,  351,
      342,  558,  361,    0,  253,  346,  344,  327,  334,  326,
      325,  558,  334,  558,  318,  333,  322,  329,  325,  324,
      558,  304,  311,  558,  308,  262,  558,  268,  558,  558,
      558,  267,  558,  558,  558,  558,  558,  264,  558,  558,
      262,  261,  276,  558,  265,  245,  558,  258,  558,  558,
      248,  233,  558,  558,  232,  238,  228,  236,  212,  223,

      558,  222,  199,  210,  216,  558,  212,  221,  281,  558,
      558,  558,  558,  558,  204,  558,  199,  558,  558,  199,
      558,  181,  172,  558,  558,  558,    0,  558,  558,  558,
      169,  558,  558,  558,  301,  307,  313,  319,  325,  331,
      337,  342,  348,  161,  139,   99,   94
    } ;

static const flex_int16_t yy_def[448] =
    {   0,
      434,    1,  435,  435,  436,  436,  437,  437,  434,  434,
      434,  438,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  439,  434,  440,
      441,  434,  434,  434,  442,  434,  434,  443,  434,  443,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,

      434,  434,  434,  434,  434,  434,  434,  434,  439,  440,
      440,  434,  441,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  444,  442,  434,  443,  443,  434,
      443,  434,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,

      434,  434,  434,  434,  434,  434,  434,  434,  434,  445,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  142,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  446,
      434,  223,  434,  434,  434,  434,  434,  434,  434,  434,

      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  447,  223,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  223,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,

      434,  434,  434,  434,  434,  434,  434,  434,  223,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  409,  434,  434,  434,
      434,  434,  434,    0,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434
    } ;

static const flex_int16_t yy_nxt[603] =
    {   0,
       10,   10,   10,   11,   12,   10,   13,   14,   15,   10,
       10,   16,   17,   10,   18,   19,   20,   21,   22,   23,
       24,   10,   25,   10,   10,   26,   10,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   10,   10,   10,   36,
       37,   10,   10,   10,   39,   39,   52,   52,   40,   40,
       42,   42,   43,   43,   46,   46,   47,   47,   49,   55,
       57,   65,   44,   44,  150,   81,   61,   50,  151,   82,
       67,   66,   68,   62,   58,   56,   59,   63,   71,   69,
       64,   70,   84,   60,   83,  105,   72,   76,   88,   73,
      129,  106,   74,  130,   77,   78,   85,   98,  384,   79,

       86,   87,   92,  344,   89,   93,   99,   90,   94,   95,
      111,  101,  112,  100,  102,  181,  103,   52,   52,   96,
      104,  182,   97,  114,  115,  148,  149,  154,  116,  161,
      155,  164,  162,  117,  118,  119,  156,  171,  194,  120,
      165,  196,  191,  290,  184,  197,  195,  121,  172,  185,
      122,  201,  123,  434,  124,  434,  125,  129,  192,  131,
      132,  111,  186,  112,  133,  210,  202,  203,  204,  134,
      135,  136,  358,  206,  129,  137,  207,  434,  129,  129,
      359,  434,  211,  138,  212,  433,  139,  213,  140,  432,
      141,  129,  142,  129,  214,  129,  215,  129,  216,  129,

      217,  129,  218,  129,  219,  129,  220,  129,  221,  431,
      222,  129,  234,  235,  434,  270,  430,  429,  223,  223,
      223,  272,  428,  425,  223,  223,  223,  223,  223,  223,
      424,  271,  273,  291,  423,  422,  421,  292,  292,  292,
      420,  419,  418,  292,  292,  292,  292,  292,  292,  345,
      345,  345,  417,  416,  415,  345,  345,  345,  345,  345,
      345,  385,  385,  385,  414,  413,  412,  385,  385,  385,
      385,  385,  385,  409,  409,  409,  411,  410,  408,  409,
      409,  409,  409,  409,  409,  426,  407,  406,  405,  427,
      427,  427,  404,  403,  402,  427,  427,  427,  427,  427,

      427,   38,   38,   38,   38,   38,   38,   41,   41,   41,
       41,   41,   41,   45,   45,   45,   45,   45,   45,   48,
       48,   48,   48,   48,   48,  109,  401,  109,  400,  109,
      109,  110,  399,  110,  110,  110,  110,  113,  398,  397,
      113,  113,  126,  396,  395,  126,  126,  126,  128,  128,
      128,  128,  128,  128,  394,  393,  392,  391,  390,  389,
      388,  387,  386,  383,  382,  381,  380,  379,  378,  377,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      366,  365,  364,  363,  362,  361,  360,  357,  356,  355,
      354,  353,  352,  351,  350,  349,  348,  347,  346,  343,

      342,  341,  340,  339,  338,  337,  336,  335,  334,  333,
      332,  331,  330,  329,  328,  327,  326,  325,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,
      312,  311,  310,  309,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  296,  295,  294,  293,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  277,  276,  275,  274,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  259,  258,  257,  256,
      255,  254,  253,  252,  251,  250,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  236,

      233,  232,  231,  230,  229,  228,  227,  226,  225,  224,
      209,  208,  205,  200,  199,  198,  193,  190,  189,  188,
      187,  183,  180,  179,  178,  177,  176,  175,  174,  173,
      170,  169,  168,  167,  166,  163,  160,  159,  158,  157,
      153,  152,  147,  146,  145,  144,  143,  127,  108,  107,
       91,   80,   75,   54,   53,   51,  434,    9,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,

      434,  434
    } ;

static const flex_int16_t yy_chk[603] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,   15,   15,    3,    4,
        5,    6,    5,    6,    7,    8,    7,    8,   12,   18,
       19,   21,    5,    6,   62,   27,   20,   12,   62,   27,
       22,   21,   22,   20,   19,   18,   19,   20,   23,   22,
       20,   22,   28,   19,   27,   34,   23,   25,   29,   23,
       48,   34,   23,   48,   25,   25,   28,   32,  447,   25,

       28,   28,   31,  446,   29,   31,   32,   29,   31,   31,
       40,   33,   40,   32,   33,   89,   33,   52,   52,   31,
       33,   89,   31,   44,   44,   61,   61,   65,   44,   70,
       65,   72,   70,   44,   44,   44,   65,   80,   98,   44,
       72,   99,   96,  445,   91,   99,   98,   44,   80,   91,
       44,  103,   44,  110,   44,  110,   44,   50,   96,   50,
       50,  111,   91,  111,   50,  444,  103,  104,  104,   50,
       50,   50,  313,  106,  128,   50,  106,  128,  129,  131,
      313,  129,  131,   50,  132,  431,   50,  132,   50,  423,
       50,  133,   50,  134,  133,  135,  134,  136,  135,  137,

      136,  138,  137,  139,  138,  140,  139,  141,  140,  422,
      141,  142,  153,  153,  142,  191,  420,  417,  142,  142,
      142,  192,  415,  408,  142,  142,  142,  142,  142,  142,
      407,  191,  192,  223,  405,  404,  403,  223,  223,  223,
      402,  400,  399,  223,  223,  223,  223,  223,  223,  292,
      292,  292,  398,  397,  396,  292,  292,  292,  292,  292,
      292,  345,  345,  345,  395,  392,  391,  345,  345,  345,
      345,  345,  345,  385,  385,  385,  388,  386,  383,  385,
      385,  385,  385,  385,  385,  409,  382,  381,  378,  409,
      409,  409,  372,  368,  366,  409,  409,  409,  409,  409,

      409,  435,  435,  435,  435,  435,  435,  436,  436,  436,
      436,  436,  436,  437,  437,  437,  437,  437,  437,  438,
      438,  438,  438,  438,  438,  439,  365,  439,  363,  439,
      439,  440,  362,  440,  440,  440,  440,  441,  360,  359,
      441,  441,  442,  358,  357,  442,  442,  442,  443,  443,
      443,  443,  443,  443,  356,  355,  353,  351,  350,  349,
      348,  347,  346,  343,  341,  340,  338,  337,  336,  334,
      332,  331,  330,  329,  328,  327,  325,  323,  322,  321,
      320,  319,  318,  317,  316,  315,  314,  312,  311,  308,
      306,  305,  303,  302,  301,  300,  299,  296,  293,  289,

      288,  287,  285,  284,  283,  282,  281,  280,  278,  276,
      274,  273,  272,  271,  270,  269,  268,  267,  266,  265,
      264,  263,  262,  261,  260,  259,  258,  257,  255,  252,
      251,  249,  248,  247,  246,  245,  244,  243,  242,  239,
      238,  237,  236,  235,  234,  233,  232,  230,  227,  224,
      209,  208,  207,  206,  205,  204,  203,  202,  201,  200,
      199,  198,  196,  195,  194,  193,  190,  189,  188,  187,
      186,  184,  183,  182,  181,  180,  179,  177,  176,  175,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,
      163,  162,  161,  160,  159,  158,  157,  156,  155,  154,

      152,  151,  150,  149,  148,  147,  146,  145,  144,  143,
      108,  107,  105,  102,  101,  100,   97,   95,   94,   93,
       92,   90,   88,   87,   86,   85,   84,   83,   82,   81,
       78,   77,   75,   74,   73,   71,   69,   68,   67,   66,
       64,   63,   60,   59,   58,   57,   55,   47,   37,   35,
       30,   26,   24,   17,   16,   14,    9,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,

      434,  434
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[129] =
    {   0,
0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Lexer.l"
#line 6 "Lexer.l"
// Remove warnings from flex
#ifdef _MSC_VER
#pragma warning( push, 0 )
#pragma warning( disable : 6011 )
#pragma warning( disable : 26819 )
#pragma warning( disable : 6387 )
#endif // _MSC_VER

#include <string>
#include <algorithm>
#include <charconv>
#include <iostream>
#include <cstdio>

#include "enable_unicode_console.hpp"

void Print(const std::string& message)
{
    std::cout << message << std::endl;
}

void PrintError(const std::string& errorMessage, const int line = -1) 
{
    std::cerr << errorMessage << std::endl;
    if (line >= 0)
        std::cerr << "Line: " << line << std::endl;
    std::cerr << std::endl;
}

void PrintComment(const std::string& comment) 
{
    Print("Found multiline comment:");
    Print("\"" + comment + "\"");
}

void PrintStringLiteral(const std::string& literal) {
    Print("Found string literal:");
    Print("\"" + literal + "\"");
}

void PrintKeyword(const std::string& keyword) {
    Print("Found keyword: " + keyword);
}

void PrintLogicalOperator(const std::string& o) {
    Print("Found logic operator: " + o);
}

void PrintAriphmeticOperator(const std::string& o) {
    Print("Found ariphmetic operator: " + o);
}

void PrintIntegerLiteral(const std::string& type, const int integer) {
    Print("Found " + type + " integer literal: " + std::to_string(integer));
}

void PrintCharacterLiteral(const char literal) {
    using namespace std::string_literals;
    Print("Found character: \'"s + literal + "\'"s);
}

#line 815 "Lexer.flex.cpp"

#line 817 "Lexer.flex.cpp"

#define INITIAL 0
#define MULTILINE_COMMENT 1
#define STRING_LITERAL 2
#define VERBATIM_STRING_LITERAL 3

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 73 "Lexer.l"



#line 77 "Lexer.l"
std::string currentStringLiteral;
std::string currentComment;
int currentInteger;
char currentCharacter;
char buffer[10];


#line 1046 "Lexer.flex.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 435 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 434 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 84 "Lexer.l"
{
                                            currentComment.clear();
                                            BEGIN(MULTILINE_COMMENT);
                                        }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 89 "Lexer.l"
{
                                            currentComment += yytext;
                                        }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 93 "Lexer.l"
{
                                            currentComment += yytext;
                                        }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 97 "Lexer.l"
{
                                            currentComment += yytext;
                                        }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 101 "Lexer.l"
{
                                            PrintComment(currentComment);
                                            BEGIN(INITIAL);
                                        }
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 106 "Lexer.l"
{
                                            PrintError("Error! Expected end of multiline comment but found end of file!", yylineno);
                                            BEGIN(INITIAL);
                                        }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 111 "Lexer.l"
{
                                            currentStringLiteral.clear();
                                            BEGIN(STRING_LITERAL);
                                        }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 116 "Lexer.l"
{
                                            currentStringLiteral += yytext;
                                        }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 119 "Lexer.l"
{
                                            std::fill(std::begin(buffer), std::end(buffer), 0);
                                            std::copy(yytext, yytext + yyleng, buffer);
                                            // Replace \ to 0. So std::sscanf can actually read this
                                            // \x74 --> 0x74
                                            buffer[0] = '0'; 
                                            std::sscanf(buffer, "%x", &currentInteger);
                                            currentStringLiteral = static_cast<char>(currentInteger);
                                        }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 128 "Lexer.l"
{
                                            currentStringLiteral += "\n";
                                        }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 131 "Lexer.l"
{
                                            currentStringLiteral += "\t";
                                        }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 134 "Lexer.l"
{
                                            currentStringLiteral += "\a";
                                        }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 137 "Lexer.l"
{
                                            currentStringLiteral += "\b";
                                        }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 140 "Lexer.l"
{
                                            currentStringLiteral += "\f";
                                        }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 143 "Lexer.l"
{
                                            PrintError("Error! Expected end of string literal but found end of line!", yylineno);
                                            BEGIN(INITIAL);
                                        }
	YY_BREAK
case YY_STATE_EOF(STRING_LITERAL):
#line 147 "Lexer.l"
{
                                            PrintError("Error! expected end of string literal but found end of file!", yylineno);
                                            BEGIN(INITIAL);
                                        }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 151 "Lexer.l"
{
                                            currentStringLiteral += "\r";
                                        }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 154 "Lexer.l"
{
                                            currentStringLiteral += "\v";
                                        }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 157 "Lexer.l"
{
                                            currentStringLiteral += "\?";
                                        }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 160 "Lexer.l"
{
                                            currentStringLiteral += "\0";
                                        }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 163 "Lexer.l"
{
                                            currentStringLiteral += "\\";
                                        }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 166 "Lexer.l"
{
                                            currentStringLiteral += "\"";
                                        }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 169 "Lexer.l"
{
                                            currentStringLiteral += "\'";
                                        }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 172 "Lexer.l"
{
                                            PrintStringLiteral(currentStringLiteral);
                                            BEGIN(INITIAL);
                                        }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 176 "Lexer.l"
{
                                            currentStringLiteral.clear();
                                            BEGIN(VERBATIM_STRING_LITERAL);
                                        }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 180 "Lexer.l"
{
                                            currentStringLiteral += "\"";
                                        }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 183 "Lexer.l"
{
                                            currentStringLiteral += yytext;
                                        }
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 186 "Lexer.l"
{
                                            currentStringLiteral += "\n";
                                        }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 189 "Lexer.l"
{
                                            PrintStringLiteral(currentStringLiteral);
                                            BEGIN(INITIAL);
                                        }
	YY_BREAK
case YY_STATE_EOF(VERBATIM_STRING_LITERAL):
#line 193 "Lexer.l"
{
                                            PrintError("Error! expected end of string literal but found end of file!", yylineno);
                                            BEGIN(INITIAL);
                                        }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 197 "Lexer.l"
{
                                            PrintError("Error! Found empty character literal!", yylineno);
                                            BEGIN(INITIAL);
                                        }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 201 "Lexer.l"
{
                                            std::fill(std::begin(buffer), std::end(buffer), 0);
                                            std::copy(yytext + 1, yytext + yyleng - 1, buffer);
                                            // Replace \ to 0. So std::sscanf can actually read this
                                            // \x74 --> 0x74
                                            buffer[0] = '0'; 
                                            std::sscanf(buffer, "%x", &currentInteger);
                                            currentCharacter = static_cast<char>(currentInteger);
                                            PrintCharacterLiteral(currentCharacter);
                                        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 211 "Lexer.l"
{
                                            PrintError("Error! Length of hexadecimal character literal cannot be larger than 4!");
                                        }
	YY_BREAK
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 214 "Lexer.l"
{
                                            PrintError("Error! Expected end of character literal but found end of line!", yylineno);
                                        }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 218 "Lexer.l"
{
                                            currentCharacter = '\n';
                                            PrintCharacterLiteral(currentCharacter);
                                        }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 222 "Lexer.l"
{
                                            currentCharacter = '\t';
                                            PrintCharacterLiteral(currentCharacter);
                                        }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 226 "Lexer.l"
{
                                            currentCharacter = '\a';
                                            PrintCharacterLiteral(currentCharacter);
                                        }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 230 "Lexer.l"
{
                                            currentCharacter = '\b';
                                            PrintCharacterLiteral(currentCharacter);
                                        }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 234 "Lexer.l"
{
                                            currentCharacter = '\f';
                                            PrintCharacterLiteral(currentCharacter);
                                        }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 238 "Lexer.l"
{
                                            currentCharacter = '\r';
                                            PrintCharacterLiteral(currentCharacter);
                                        }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 242 "Lexer.l"
{
                                            currentCharacter = '\v';
                                            PrintCharacterLiteral(currentCharacter);
                                        }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 246 "Lexer.l"
{
                                            currentCharacter = '\?';
                                            PrintCharacterLiteral(currentCharacter);
                                        }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 250 "Lexer.l"
{
                                            currentCharacter = '\0';
                                            PrintCharacterLiteral(currentCharacter);
                                        }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 254 "Lexer.l"
{
                                            currentCharacter = '\\';
                                            PrintCharacterLiteral(currentCharacter);
                                        }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 258 "Lexer.l"
{      
                                            currentCharacter = '\"';
                                            PrintCharacterLiteral(currentCharacter);
                                        }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 262 "Lexer.l"
{
                                            currentCharacter = '\'';
                                            PrintCharacterLiteral(currentCharacter);
                                        }
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 266 "Lexer.l"
{
                                            currentCharacter = yytext[1];
                                            PrintCharacterLiteral(currentCharacter);
                                        }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 271 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 272 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 273 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 274 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 275 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 276 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 277 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 278 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 279 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 280 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 281 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 282 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 283 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 284 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 285 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 286 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 287 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 288 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 289 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 290 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 291 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 292 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 293 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 294 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 295 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 296 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 297 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 298 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 299 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 300 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 301 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 302 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 303 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 304 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 305 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 306 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 307 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 308 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 309 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 310 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 311 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 312 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 313 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 314 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 315 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 316 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 317 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 318 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 319 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 320 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 321 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 322 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 323 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 324 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 325 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 326 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 327 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 328 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 329 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 330 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 331 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 332 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 333 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 334 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 335 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 336 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 337 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 338 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 339 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 340 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 341 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 342 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 343 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 344 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 345 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 346 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 347 "Lexer.l"
{ PrintKeyword(yytext); } 
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 349 "Lexer.l"
{ PrintAriphmeticOperator(yytext); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 350 "Lexer.l"
{ PrintLogicalOperator(yytext); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 352 "Lexer.l"
{ Print("Found left curly brace"); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 354 "Lexer.l"
{ 
                                            std::sscanf(yytext, "%o", &currentInteger);
                                            PrintIntegerLiteral("octal", currentInteger); 
                                        }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 358 "Lexer.l"
{ 
                                            std::sscanf(yytext, "%d", &currentInteger);
                                            PrintIntegerLiteral("decimal", currentInteger); 
                                        }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 362 "Lexer.l"
{ 
                                            std::sscanf(yytext, "%x", &currentInteger);
                                            PrintIntegerLiteral("hexadecimal", currentInteger); 
                                        }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 367 "Lexer.l"
ECHO;
	YY_BREAK
#line 1906 "Lexer.flex.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 435 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 435 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 434);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 367 "Lexer.l"

#ifdef _MSC_VER
#pragma warning( pop )
#endif // _MSC_VER

int main(int argc, char** argv) 
{
    if (argc > 1)
    {
        const auto errorCode = fopen_s(&yyin, argv[1], "r");
    }
    else 
    {
        yyin = stdin;
    }

    yylex();
}
